ASLTS: applied the patch I gave to david and Bob.

diff --git a/tests/aslts/Makefile.def b/tests/aslts/Makefile.def
--- a/tests/aslts/Makefile.def
+++ b/tests/aslts/Makefile.def
@@ -25,9 +25,7 @@
 SETOF_INDEXES= 0 1 2 3
 SETOF_AMLDIRS= nopt/32 nopt/64 opt/32 opt/64
 SETOF_ASLFAGS= "-oa -r 1" "-oa -r 2" "-r 1" "-r 2"
-ASL_OUTPUT_FLAGS= " -l -sc -sa -ic -ta -ts -so -lm -ln -ls -li"
-ASL_CORE_FLAGS= "-of -cr -vs"
-COMMON_ASL_FLAGS= $(ASL_CORE_FLAGS)$(ASL_OUTPUT_FLAGS)
+COMMON_ASL_FLAGS= "-of -cr -vs -l -sc -sa -ic -ta -ts -so -lm -ln -ls -li"
 
 COMPILER_LOG="$(TOP)/tmp/aml/$(aslversion)/compile.txt"
 COMPILER_ERROR_LOG="$(TOP)/tmp/aml/$(aslversion)/error.txt"
@@ -74,15 +72,7 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 			for j in ${ASLMOD} $(ASLMODADD); do \
 				echo "---- Compile: $$j.asl" >> $(COMPILER_LOG); \
 				>&2 printf "%-18s" "    Type: $$CUR_AMLDIR "; \
-				>&2 printf  "Convert"; \
-				"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) -od -ca $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
-				if [ -f $$j.dsl ]; then \
-					>&2 printf " [success]"; \
-				fi; \
-				for j in ${AMLMOD}; do \
-					rm -f $$j.aml; \
-				done; \
-				>&2 printf  " => Compile"; \
+				>&2 printf  "Compile"; \
 				"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
 				ret=$$?; \
 				echo "" >> $(COMPILER_LOG); \
@@ -95,17 +85,16 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 						if [ ! -f $$k-aslminus.dsl ]; then \
 							>&2 printf " [[ Error: disassembly failed of $$k.aml failed ]]\n"; \
 							>&2 printf "          Flags used: -p $$k-aslminus -cr -vs $$CUR_ASLFLAGS $(ADD_ASLFLAGS) -od -dl\n\n"; \
-							#exit 1; \
+							exit 1; \
 						fi; \
 						>&2 printf " => Recompile"; \
 						echo "---- Recompile: $$k.dsl" >> $(COMPILER_LOG); \
 						echo "---- Recompile: $$k.dsl" >> $(COMPILER_ERROR_LOG); \
 						"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$k-aslminus.dsl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
-						"$(ASL)" -p $k-convert $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.dsl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
 						if [ ! -f $$k-aslminus.aml ]; then \
 							>&2 printf " [[ Error: re-compilation of $$k-aslminus.dsl failed]]\n"; \
 							>&2 printf "          Flags used: $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS)\n\n"; \
-							#exit 1; \
+							exit 1; \
 						fi; \
 						rm $$k-aslminus.asm; \
 						rm $$k-aslminus.c; \
@@ -119,9 +108,8 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 						if [ $$CUR_AMLDIR = "nopt/32" ] || [ $$CUR_AMLDIR = "nopt/64" ]; then \
 							>&2 printf " => Binary compare"; \
 							acpibin -c $$k.aml $$k-aslminus.aml >> comparison_output.txt; \
-							acpibin -c $$k.aml $$k-convert.aml >> comparison_output.txt; \
 							if [ $$? != 0 ]; then \
-								>&2 printf " [[ Error: comparison of $$k.aml and $$k-convert.aml do not match ]]"; \
+								>&2 printf " [[ Error: comparison of $$k.aml and $$k-aslminus.aml do not match ]]"; \
 								cat comparison_output.txt | sed '1,/^Error/d' | sed 's/Error - Byte mismatch at offset     /         => /g' | sed -n 1,10p > comparison_output.txt;\
 								>&2 printf "\n"; \
 								cat comparison_output.txt >&2 ; \
@@ -136,24 +124,23 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 						fi; \
 						>&2 printf " => Done"; \
 					done; \
-				else \
-					>&2 printf " => Removing files"; \
-					rm $$j.asm; \
-					rm $$j.c; \
-					rm $$j.h; \
-					rm $$j.i; \
-					rm $$j.hex; \
-					rm $$j.lst; \
-					rm $$j.map; \
-					rm $$j.nsp; \
-					rm $$j.offset.h; \
-					rm $$j.src; \
-					>&2 printf " => Done"; \
 				fi; \
+				>&2 printf " => Removing files"; \
+				rm $$j.asm; \
+				rm $$j.c; \
+				rm $$j.h; \
+				rm $$j.i; \
+				rm $$j.hex; \
+				rm $$j.lst; \
+				rm $$j.map; \
+				rm $$j.nsp; \
+				rm $$j.offset.h; \
+				rm $$j.src; \
+				>&2 printf " => Done"; \
 				if [ $$ret != 0 ]; then \
 					rval=1; \
 					>&2 echo "**** Unexpected iASL failure in $$dd/$$j.asl!"; \
-					#exit 1; \
+					exit 1; \
 				fi; \
 			done; \
 			>&2 echo ""; \
@@ -163,7 +150,7 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 				echo "---- Move: $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR" >> $(COMPILER_LOG); \
 				mv $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR; \
 				ret=$$?; \
-				if [ $$ret != 0 ]; then rval=2; echo "**** mv failed!"; break; fi; \
+				if [ $$ret != 0 ]; then rval=2; echo "**** mv failed!" >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); break; fi; \
 			done; \
 		done; \
 	else \
@@ -223,7 +210,7 @@ install_test_case:
 									echo "Bad dir: aslts/tmp"; exit 1; \
 								else \
 									cd "$$testcasedir"; \
-									export aslversion; make install_all_modes_of_test_case; \
+									export aslversion; make install_all_modes_of_test_case OPT=$(OPT); \
 								fi; \
 							fi; \
 						fi; \
