Tests: Add -cr iASL option to ASLTS makefile.
This option disables resource descriptor error checking.
ASLTS tests byte-by-byte descriptor construction, thus we
do not want to error check the values at compile time.

diff --git a/tests/aslts/Makefile.def b/tests/aslts/Makefile.def
--- a/tests/aslts/Makefile.def
+++ b/tests/aslts/Makefile.def
@@ -25,7 +25,7 @@
 SETOF_INDEXES= 0 1 2 3
 SETOF_AMLDIRS= nopt/32 nopt/64 opt/32 opt/64
 SETOF_ASLFAGS= "-oa -r 1" "-oa -r 2" "-r 1" "-r 2"
-ASL_QUIET_MODE= "-vs -va"
+COMMON_ASL_FLAGS= "-cr -vs -va"
 
 # Create general directory
 
@@ -57,15 +57,15 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 			shift $$i; \
 			CUR_ASLFLAGS=$$1; \
 			for j in ${ASLMOD} $(ASLMODADD); do \
-				"$(ASL)" $$CUR_ASLFLAGS "$(ASL_QUIET_MODE)" $(ADD_ASLFLAGS) $$j.asl; \
+				"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.asl; \
 				ret=$$?; \
-				if [ $$ret != 0 ]; then rval=1; echo "iASL failed!"; break; fi; \
+				if [ $$ret != 0 ]; then rval=1; echo "**** Unexpected iASL failure!"; exit 1; fi; \
 			done; \
 			if [ $$ret != 0 ]; then break; fi; \
 			for j in ${AMLMOD}; do \
 				mv $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR; \
 				ret=$$?; \
-				if [ $$ret != 0 ]; then rval=2; echo "mv failed!"; break; fi; \
+				if [ $$ret != 0 ]; then rval=2; echo "**** mv failed!"; break; fi; \
 			done; \
 		done; \
 	else \
@@ -150,7 +150,7 @@ compile_test_case:
 			for j in ${ASLMOD} $(ASLMODADD); do \
 				"$(ASL)" $$CUR_ASLFLAGS $(ADD_ASLFLAGS) $$j.asl; \
 				ret=$$?; \
-				if [ $$ret != 0 ]; then rval=1; echo "iASL failed!"; break; fi; \
+				if [ $$ret != 0 ]; then rval=1; echo "**** Unexpected iASL failure!"; exit 1; fi; \
 			done; \
 		done; \
 	else \
