Testsuite Makefile: added diasm option

diff --git a/tests/aslts/Makefile.def b/tests/aslts/Makefile.def
--- a/tests/aslts/Makefile.def
+++ b/tests/aslts/Makefile.def
@@ -67,35 +67,66 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 			for j in ${AMLMOD}; do \
 				rm -f $$j.aml; \
 			done; \
-			for j in ${ASLMOD} $(ASLMODADD); do \
-				echo "---- Compile: $$j.asl" >> $(COMPILER_LOG); \
-				"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
-			        for k in ${AMLMOD}; do \
-					>&2 echo "---- Disassemble: $$k.aml"; \
-					"$(ASL)" -df $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) -dl $$k.aml; \
-					>&2 echo "---- Recompile: $$k.dsl"; \
-					"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$k.dsl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+			if [ $(OPT) = 1 ]; then \
+				for j in ${ASLMOD} $(ASLMODADD); do \
+					echo "---- Compile: $$j.asl" >> $(COMPILER_LOG); \
+					"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+				        for k in ${AMLMOD}; do \
+						>&2 echo "---- Disassemble: $$k.aml"; \
+						"$(ASL)" -df $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) -dl $$k.aml; \
+						>&2 echo "---- Recompile: $$k.dsl"; \
+						"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$k.dsl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+					done; \
+					ret=$$?; \
+					echo "" >> $(COMPILER_LOG); \
+					rm $$j.asm; \
+					rm $$j.c; \
+					rm $$j.h; \
+					rm $$j.i; \
+					rm $$j.hex; \
+					rm $$j.lst; \
+					rm $$j.map; \
+					rm $$j.nsp; \
+					rm $$j.offset.h; \
+					rm $$j.src; \
 				done; \
-				ret=$$?; \
-				echo "" >> $(COMPILER_LOG); \
-				rm $$j.asm; \
-				rm $$j.c; \
-				rm $$j.h; \
-				rm $$j.i; \
-				rm $$j.hex; \
-				rm $$j.lst; \
-				rm $$j.map; \
-				rm $$j.nsp; \
-				rm $$j.offset.h; \
-				rm $$j.src; \
-			done; \
-			for j in ${AMLMOD}; do \
-				ls -l $$j.aml >> $(COMPILER_LOG); \
-				echo "---- Move: $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR" >> $(COMPILER_LOG); \
-				mv $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR; \
-				ret=$$?; \
-				if [ $$ret != 0 ]; then rval=2; echo "**** mv failed!"; break; fi; \
-			done; \
+				for j in ${AMLMOD}; do \
+					ls -l $$j.aml >> $(COMPILER_LOG); \
+					echo "---- Move: $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR" >> $(COMPILER_LOG); \
+					mv $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR; \
+					ret=$$?; \
+					if [ $$ret != 0 ]; then rval=2; echo "**** mv failed!"; break; fi; \
+				done; \
+			elif [ $(OPT) = 0 ]; then \
+				for j in ${ASLMOD} $(ASLMODADD); do \
+					echo "---- Compile: $$j.asl" >> $(COMPILER_LOG); \
+					"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+					ret=$$?; \
+					echo "" >> $(COMPILER_LOG); \
+					rm $$j.asm; \
+					rm $$j.c; \
+					rm $$j.h; \
+					rm $$j.i; \
+					rm $$j.hex; \
+					rm $$j.lst; \
+					rm $$j.map; \
+					rm $$j.nsp; \
+					rm $$j.offset.h; \
+					rm $$j.src; \
+					if [ $$ret != 0 ]; then \
+						rval = 1; \
+						echo "**** Unexpected iASL failure in $$dd/$$j.asl!"; \
+						exit 1; \
+					fi; \
+					for j in ${AMLMOD}; do \
+						ls -l $$j.aml >> $(COMPILER_LOG); \
+						echo "---- Move: $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR" >> $(COMPILER_LOG); \
+						mv $$j.aml $(TOP)/tmp/aml/$(aslversion)/$$CUR_AMLDIR; \
+						ret=$$?; \
+						if [ $$ret != 0 ]; then rval=2; echo "**** mv failed!"; break; fi; \
+					done; \
+				done; \
+			fi; \
 		done; \
 	else \
 		echo "Bad iASL 0: <$(ASL)> does not exist"; \
@@ -154,7 +185,7 @@ install_test_case:
 									echo "Bad dir: aslts/tmp"; exit 1; \
 								else \
 									cd "$$testcasedir"; \
-									export aslversion; make install_all_modes_of_test_case; \
+									export aslversion; make install_all_modes_of_test_case OPT=$(OPT); \
 								fi; \
 							fi; \
 						fi; \
