ASLTS: adding converter binary compare

diff --git a/tests/aslts/Makefile.def b/tests/aslts/Makefile.def
--- a/tests/aslts/Makefile.def
+++ b/tests/aslts/Makefile.def
@@ -71,8 +71,13 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 			done; \
 			for j in ${ASLMOD} $(ASLMODADD); do \
 				echo "---- Compile: $$j.asl" >> $(COMPILER_LOG); \
+				echo "---- Compile: $$j.asl" >> $(COMPILER_LOG); \
 				>&2 printf "%-18s" "    Type: $$CUR_AMLDIR "; \
-				>&2 printf  "Compile"; \
+				>&2 printf "Convert"; \
+				"$(ASL)" $$CUR_ASLFLAGS $(ADD_ASLFLAGS) -of -cr -vs -ca $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+				>&2 printf " => Re-compile"; \
+				"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.dsl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
+				>&2 printf " => Compile"; \
 				"$(ASL)" $$CUR_ASLFLAGS "$(COMMON_ASL_FLAGS)" $(ADD_ASLFLAGS) $$j.asl >> $(COMPILER_LOG) 2>> $(COMPILER_ERROR_LOG); \
 				ret=$$?; \
 				echo "" >> $(COMPILER_LOG); \
@@ -155,6 +160,17 @@ install_all_modes_of_test_case:	${SETOF_AMLDIRS:%=$(TOP)/tmp/aml/$(aslversion)/%
 								rm $$k-aslplus.aml; \
 								rm $$k-aslplus.dsl; \
 							fi; \
+							>&2 printf " => Converted aml compare"; \
+							acpibin -c $$k.aml $$j.aml >> comparison_output.txt; \
+							if [ $$? != 0 ]; then \
+								>&2 printf " [[ Error: comparison of $$k.aml and $$j.aml do not match ]]"; \
+								cat comparison_output.txt | sed '1,/^Error/d' | sed 's/Error - Byte mismatch at offset     /         => /g' | sed -n 1,10p > comparison_output.txt; \
+								>&2 printf "\n"; \
+								cat comparison_output.txt >&2 ; \
+								>&2 printf "        "; \
+								#exit 1; \
+							fi; \
+							rm $$j.aml; \
 						fi; \
 						>&2 printf " => Done"; \
 					done; \
